// Generated by LiveScript 1.2.0
var request, cheerio, out$ = typeof exports != 'undefined' && exports || this;
request = require('request');
cheerio = require('cheerio');
out$.avaliableTitles = avaliableTitles;
function avaliableTitles(url, done){
  return request(url, function(err, res, body){
    var $, get, layers, result;
    $ = cheerio.load(body, {
      xmlMode: true
    });
    get = function(o, q){
      return $(o).children(q);
    };
    layers = $('Layer');
    result = {
      count: layers.length,
      tiles: {}
    };
    layers.each(function(idx){
      var id, name, format, url;
      id = get(this, "ows\\:Identifier").text();
      name = get(this, "ows\\:Title").text();
      format = get(this, 'Format').text().replace('image/', '');
      url = get(this, 'ResourceURL').attr('template');
      return result['tiles'][id] = {
        name: name,
        format: format,
        url: url
      };
    });
    return done(result);
  });
}