// Generated by LiveScript 1.2.0
var out$ = typeof exports != 'undefined' && exports || this;
out$.avaliableTitles = avaliableTitles;
function avaliableTitles(url, done){
  var result;
  result = {
    tainan_1875: {
      name: '臺灣府城街道圖'
    }
  };
  return done(result);
}