// Generated by LiveScript 1.2.0
var request, cheerio, out$ = typeof exports != 'undefined' && exports || this;
request = require('request');
cheerio = require('cheerio');
out$.avaliableTitles = avaliableTitles;
function avaliableTitles(url, done){
  return request(url, function(err, res, body){
    var c, get, layers, result;
    if (err) {
      done(err, {
        count: 0,
        titles: {}
      });
    }
    c = cheerio.load(body, {
      xmlMode: true
    });
    get = function(o, q){
      return c(o).children(q);
    };
    layers = c('Contents').find('Layer');
    result = {
      count: layers.length,
      titles: {}
    };
    layers.each(function(idx){
      var id, name, format, url;
      id = get(this, "ows\\:Identifier").text();
      name = get(this, "ows\\:Title").text();
      format = get(this, 'Format').text().replace('image/', '');
      url = get(this, 'ResourceURL').attr('template');
      return result['titles'][id] = {
        id: id,
        name: name,
        format: format,
        url: url
      };
    });
    return done(err, result);
  });
}